#import "common.typ": bdefinition, btheorem, blemma, bproposition, bexample, bnotice

== Compiler Architecture: From Source Strings to Target Executables

A compiler is a software pipeline that transforms source code written in a high-level language into an equivalent target representation (such as stack bytecode or native machine assembly).

=== Classical Multi-Pass Pipeline

The compilation process is structured into distinct, modular phases:
1. *Lexical Analysis (Scanning / Lexing):* Converts a raw, unstructured stream of characters $c_1, c_2, dots in Sigma^*$ into a sequence of discrete lexical tokens $T_1, T_2, dots in cal(T)^*$. Comments and extraneous whitespace are filtered out, and line/column source positions are attached.
2. *Syntactic Analysis (Parsing):* Consumes the token stream and verifies conformance with a formal context-free grammar (CFG). It generates a hierarchical tree structure: the *Abstract Syntax Tree (AST)*.
3. *Semantic Analysis & Type Checking:* Traverses the AST to verify scope rules, resolve identifier bindings in symbol tables, and enforce type constraints.
4. *Intermediate Code Generation & Optimization:* Translates the typed AST into an intermediate representation (IR), applying constant folding, dead-code elimination, and register/stack optimization.
5. *Code Generation (Target Emission):* Emits target assembly instructions, assigns memory layouts, and resolves branch labels.

=== Formal Grammars and Chomsky Hierarchy

#bdefinition(caption: "Context-Free Grammar (CFG)")[
A Context-Free Grammar is a 4-tuple $G = (V, Sigma, R, S)$ where:
- $V$ is a finite set of *non-terminal* characters (syntactic categories).
- $Sigma$ is a finite set of *terminal* characters (tokens), disjoint from $V$.
- $R subset.eq V times (V union Sigma)^*$ is a finite set of *production rules*, written $A -> alpha$.
- $S in V$ is the distinguished *start symbol*.
]

Grammars are commonly rendered in *Backus-Naur Form (BNF)*:
$ "Expr" -> "Expr" space "+" space "Term" bar.v "Term" $
$ "Term" -> "Term" space "*" space "Factor" bar.v "Factor" $
$ "Factor" -> "(" space "Expr" space ")" bar.v "number" $

=== Shift-Reduce Parsing & LR Automata

Deterministic bottom-up parsers, including those generated by *Yacc* and *Happy*, belong to the family of $L R(k)$ parsers (*Left-to-right scanning*, *Rightmost derivation in reverse*, with $k$ tokens of lookahead, typically $k=1$ or LALR(1)).

An LR parser maintains an internal stack of states and symbols and operates via four fundamental actions:
1. *Shift:* Read the current lookahead token from the input stream, push it along with the new DFA state onto the parse stack, and advance the input cursor.
2. *Reduce:* When the top of the stack matches the right-hand side of a production rule $A -> alpha$, pop $|alpha|$ symbols from the stack and push the non-terminal $A$, triggering the associated semantic action.
3. *Accept:* The input is exhausted, and the start symbol $S$ occupies the stack; parsing successfully terminates.
4. *Error:* No valid shift or reduce transition exists for the current state and lookahead token.

#bnotice(caption: "Grammar Ambiguities: Shift/Reduce and Reduce/Reduce Conflicts")[
When a grammar admits multiple parse trees for the same input string:
- *Shift/Reduce Conflict:* The parser cannot decide whether to shift the next token or reduce the current stack items (e.g., the classic "dangling-else" dilemma).
- *Reduce/Reduce Conflict:* Two distinct grammar rules simultaneously match the current stack top, indicating fundamental syntactic ambiguity or poor grammar factoring.
Resolving these conflicts requires declaring operator precedence (`%left`, `%right`, `%nonassoc`) or refactoring non-terminals.
]
